// initialize-hook.js
// Initializes the Transfer Hook's ExtraAccountMetaList PDA for a given mint.
// Usage: node initialize-hook.js <MINT_ADDRESS>

const { Connection, PublicKey, Keypair, SystemProgram } = require('@solana/web3.js');
const anchor = require('@coral-xyz/anchor');
const { readFileSync, existsSync } = require('fs');
const path = require('path');

async function main() {
  // 1. Parse mint address from command line
  const mintAddress = process.argv[2];
  if (!mintAddress) {
    console.error('❌ Usage: node initialize-hook.js <MINT_ADDRESS>');
    console.error('   Example: node initialize-hook.js 7xY...');
    process.exit(1);
  }

  let mint;
  try {
    mint = new PublicKey(mintAddress);
  } catch (e) {
    console.error('❌ Invalid mint address:', e.message);
    process.exit(1);
  }

  // 2. Load deployer key (same as used in devnet-deploy.js)
  const vaultPath = path.resolve('systems/auth/vault.json');
  let deployer;
  try {
    if (existsSync(vaultPath)) {
      const vault = JSON.parse(readFileSync(vaultPath, 'utf8'));
      const pkArray = vault.solana?.deployer_pk;
      if (pkArray) {
        deployer = Keypair.fromSecretKey(Uint8Array.from(pkArray));
        console.log('🔑 Loaded deployer from vault.');
      } else {
        throw new Error('No deployer_pk in vault');
      }
    } else {
      throw new Error('Vault not found');
    }
  } catch (e) {
    // Fallback to local devnet-deployer.json
    const localKeyPath = path.join(process.cwd(), 'devnet-deployer.json');
    if (existsSync(localKeyPath)) {
      try {
        const secretKey = JSON.parse(readFileSync(localKeyPath, 'utf8'));
        deployer = Keypair.fromSecretKey(Uint8Array.from(secretKey));
        console.log('🔑 Loaded deployer from local key file.');
      } catch (e2) {
        console.error('❌ Failed to load local key:', e2.message);
        process.exit(1);
      }
    } else {
      console.error('❌ No deployer key found. Run the mint script (devnet-deploy.js) first.');
      process.exit(1);
    }
  }

  // 3. Connect to devnet
  const connection = new Connection('https://api.devnet.solana.com', 'confirmed');
  console.log(`🔧 Initializing Transfer Hook PDA for mint: ${mint.toString()}`);
  console.log(`👤 Deployer: ${deployer.publicKey.toString()}`);

  // 4. Load Anchor program
  // Program ID - UPDATE THIS IF IT CHANGED DURING DEPLOYMENT!
  const programId = new PublicKey('DjS53vAF7A6xhQiUS1iAPGqsKNAxjrBPMXAaVyXj4H5f');
  console.log(`🔄 Using Hook Program ID: ${programId.toString()}`);

  // IDL path (generated by anchor build)
  const idlPath = path.join(__dirname, '../token/programs/target/idl/grid_transfer_hook.json');
  if (!existsSync(idlPath)) {
    console.error('❌ IDL file not found. Did you run "anchor build" in Step 1?');
    console.error(`   Expected at: ${idlPath}`);
    process.exit(1);
  }

  let idl;
  try {
    idl = JSON.parse(readFileSync(idlPath, 'utf8'));
  } catch (e) {
    console.error('❌ Failed to parse IDL:', e.message);
    process.exit(1);
  }

  const provider = new anchor.AnchorProvider(connection, new anchor.Wallet(deployer), {});
  const program = new anchor.Program(idl, programId, provider);

  // 5. Derive PDA for ExtraAccountMetaList
  const [extraAccountMetaListPDA] = PublicKey.findProgramAddressSync(
    [Buffer.from('extra-account-metas'), mint.toBuffer()],
    program.programId
  );
  console.log(`📌 PDA Address: ${extraAccountMetaListPDA.toString()}`);

  // 6. Initialize
  try {
    console.log('📡 Sending initialization transaction...');
    const tx = await program.methods
      .initializeExtraAccountMetaList()
      .accounts({
        payer: deployer.publicKey,
        extraAccountMetaList: extraAccountMetaListPDA,
        mint: mint,
        tokenProgram: new PublicKey('TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb'), // TOKEN_2022_PROGRAM_ID
        associatedTokenProgram: new PublicKey('ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'),
        systemProgram: SystemProgram.programId,
      })
      .rpc();
    
    console.log(`✅ Transfer Hook PDA initialized successfully!`);
    console.log(`🔗 Transaction: https://explorer.solana.com/tx/${tx}?cluster=devnet`);
  } catch (e) {
    console.error('❌ Initialization failed:', e.message);
    if (e.logs) {
      console.error('Logs:');
      e.logs.forEach(log => console.error('   ', log));
    }
    process.exit(1);
  }
}

main().catch(console.error);
